name: archival_system
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.4
  connectivity_plus: ^6.1.3
  file_picker: ^9.0.0
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_tesseract_ocr: ^0.4.26
  google_fonts: ^6.2.1
  google_ml_kit: ^0.19.0
  image: ^4.3.0
  lottie: ^3.3.0
  path_provider: ^2.1.5
  pdf_image_renderer: ^1.0.1
  pdf_render: ^1.4.12
  provider: ^6.1.2
  timeago: ^3.7.0
  pdf: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  firebase_data_connect: ^0.1.2+5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/university-of-ibadan-logo-transparent.png
    - assets/lottie/email_sent.json
    - assets/lottie/document-illustration.json
